name: Weekly Opinion Summary

on:
  schedule:
    - cron: '0 2 * * 1'  # 2AM UTC = 9AM Monday Vietnam time
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  send-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run summary script
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python main.py
